/* Croatian long-form content for sensors, actuators, faults, DTCs and groups.
   Loaded after info.js; also registers short names in ECU.HR so t(englishName) works. */
(function () {
  const ECU = window.ECU;

  const sensors = {
    ckp: {
      name: 'Položaj radilice', tech: 'Induktivni (VR) ili Hallov senzor',
      what: 'Točan položaj i brzina vrtnje radilice (koljenastog vratila). To je najvažniji ulaz — bez CKP signala nema ni iskre ni ubrizgavanja.',
      how: 'Na radilicu je pričvršćen davački kotač 60-2 sa zubima. Senzor „vidi” svaki zub koji prođe. Induktivni (VR) senzor stvara izmjenični napon čija amplituda raste s brzinom; Hallov senzor daje čisti pravokutni signal 0/5 V. Dva zuba nedostaju — ta duga praznina je referentna oznaka pomoću koje ECU zna gdje je GMT.',
      ecu: 'Broji zube i tako zna kut radilice na ~6° točno (interpolacijom ispod 0.5°). Iz vremena između zubi računa okretaje. Male promjene brzine tijekom svakog radnog takta koriste se za otkrivanje izostanka paljenja. Svako ubrizgavanje i paljenje planira se u stupnjevima radilice.',
      typical: 'Pokretanje 200–300 o/min · Prazni hod 750–900 o/min · Signal: 60 impulsa po okretaju minus 2',
      fail: 'Motor ne pali ili se odmah gasi. Okretomjer pada na nulu. Kod greške P0335.',
    },
    cmp: {
      name: 'Položaj bregastog vratila', tech: 'Hallov senzor',
      what: 'U kojem je od dva okretaja radilice motor. Bregasto vratilo okrene se jednom na svaka dva okretaja radilice, pa razlikuje takt kompresije od takta ispuha.',
      how: 'Hallov senzor očitava zub na usisnom bregastom vratilu. Daje jedan impuls na svakih 720° radilice. Usporedbom impulsa s CKP prazninom mjeri se i koliko je varijabilno upravljanje ventilima (VVT) zakrenulo bregasto vratilo.',
      ecu: 'Samo s CKP-om ECU zna da su cilindri 1 i 4 u GMT — ali ne i koji od njih pali. Kad stigne impuls bregastog, prelazi na potpuno sekvencijalno ubrizgavanje i zasebnu bobinu za svaki cilindar. Koristi ga i za regulaciju VVT-a.',
      typical: '1 impuls na 720° · Faza bregastog 0–40° naprijed',
      fail: 'Motor i dalje radi u rezervnom načinu „skupnog ubrizgavanja / izgubljene iskre” — brizgaljke rade u parovima, obje bobine para pale istovremeno. Nešto veća potrošnja. Kod greške P0340.',
    },
    maf: {
      name: 'Mjerač mase zraka', tech: 'Anemometar s grijanim filmom',
      what: 'Masa zraka koja svake sekunde ulazi u motor — najizravnija mjera opterećenja motora.',
      how: 'U struji usisnog zraka nalazi se grijani film. Zrak koji struji hladi ga, a elektronika povećava struju kako bi ga držala na stalnoj temperaturi iznad temperature usisnog zraka. Ta se struja pretvara u napon ili frekvenciju proporcionalnu masi zraka (ne volumenu, pa se nadmorska visina i temperatura uzimaju u obzir automatski).',
      ecu: 'Zrak po cilindru = MAF ÷ (okretaji ÷ 30). Taj broj („opterećenje”) određuje količinu goriva i kut pretpaljenja iz kalibracijskih mapa.',
      typical: 'Prazni hod 2–4 g/s · Krstarenje 10–25 g/s · 2.0 atmosferski pri maksimalnim okretajima ≈ 120 g/s',
      fail: 'ECU prelazi na speed-density (MAP + okretaji + temperatura). Kod greške P0101/P0102.',
    },
    map: {
      name: 'Apsolutni tlak u usisnoj grani', tech: 'Piezootpornički silicijski senzor deformacije',
      what: 'Apsolutni tlak u usisnoj grani, iza leptira. Nizak (podtlak) u praznom hodu, blizu atmosferskog pri punom gasu, iznad atmosferskog pod tlakom punjenja.',
      how: 'Silicijska membrana s vakuumskom referencom s jedne strane savija se pod tlakom. Tenzometri na njoj čine Wheatstoneov most; pojačalo daje 0.5–4.5 V.',
      ecu: 'Za speed-density izračun zraka (rezerva MAF-u ili primarni izvor na mnogim turbo motorima), očitanje barometarskog tlaka pri uključenju kontakta i provjeru vjerodostojnosti MAF-a.',
      typical: 'Prazni hod 28–40 kPa · Pun gas atmosferski ≈ 98 kPa · Tlak punjenja 150–250 kPa',
      fail: 'ECU koristi MAF + kut leptira. Kod greške P0107/P0108.',
    },
    tps: {
      name: 'Položaj leptira (dvostruki)', tech: 'Hallov / potenciometar, redundantni kanali',
      what: 'Stvarno otvaranje elektroničkog leptira.',
      how: 'Dva neovisna senzora suprotnih nagiba (jedan raste 0.5→4.5 V, drugi pada). Moraju se uvijek slagati — to je sigurnosni zahtjev za elektronički gas (drive-by-wire).',
      ecu: 'Regulacija motora leptira u zatvorenoj petlji, prepoznavanje praznog hoda, obogaćivanje pri ubrzanju i provjere vjerodostojnosti u odnosu na senzor papučice.',
      typical: 'Prazni hod 3–8 % (zrak za prazni hod dozira sam leptir) · Pun gas 100 %',
      fail: 'Kanali se ne slažu → motor leptira isključen, opruga drži ~7 % otvorenosti („nužni rad”), lampica EPC. Kod greške P0121.',
    },
    app: {
      name: 'Položaj papučice gasa', tech: 'Dvostruki Hallov senzor',
      what: 'Koliko vozač pritišće papučicu — to je zahtjev za momentom, a ne izravna naredba leptiru.',
      how: 'Dva Hallova senzora u sklopu papučice, drugi kanal na pola napona, stalno se uspoređuju.',
      ecu: 'ECU pretvara postotak papučice u kut leptira (progresivna mapa), dodaje zrak za prazni hod i ograničava ga radi zaštite (previsok tlak punjenja, nužni rad, kontrola proklizavanja).',
      typical: '0–100 %',
      fail: 'Nužni rad, motor samo na povišenom praznom hodu.',
    },
    baro: {
      name: 'Barometarski tlak', tech: 'Silicijski senzor deformacije (u ECU-u)',
      what: 'Tlak okolnog zraka (nadmorska visina i vrijeme).',
      how: 'Obično senzor tlaka zalemljen na pločicu ECU-a; također se ponovno očitava s MAP senzora pri uključenju kontakta prije pokretanja.',
      ecu: 'Korigira gorivo i paljenje prema nadmorskoj visini, računa tlak punjenja (= MAP − baro) i skalira granicu brzine turbine.',
      typical: 'Razina mora 101.3 kPa · 2000 m ≈ 80 kPa',
      fail: 'Koristi se zadana vrijednost 101.3 kPa.',
    },
    o2up: {
      name: 'Prednja lambda sonda (B1S1)', tech: 'Cirkonijska (uskopojasna), grijana',
      what: 'Je li ispuh bogatiji ili siromašniji od stehiometrijskog (omjer zraka i goriva 14.7 : 1, λ = 1).',
      how: 'Cirkonijski keramički naprstak provodi ione kisika kad je vruć (>350 °C). Razlika kisika između ispuha i vanjskog zraka stvara napon: ~0.9 V bogato, ~0.1 V siromašno, s naglim prijelazom točno na λ = 1. Ugrađeni grijač dovodi je na radnu temperaturu u nekoliko sekundi nakon paljenja.',
      ecu: 'Srce regulacije goriva u ZATVORENOJ PETLJI. Kad napon pokazuje bogato, ECU postupno smanjuje gorivo; kad pokazuje siromašno, povećava ga. Zbog toga signal oscilira 1–2 puta u sekundi oko λ = 1 — upravo ono što treba katalizatoru.',
      typical: 'Prebacivanje 0.1 ↔ 0.9 V na 0.5–2 Hz u zatvorenoj petlji',
      fail: 'Nema prebacivanja → gorivo u otvorenoj petlji, MIL. Kod greške P0134.',
    },
    o2dn: {
      name: 'Stražnja lambda sonda (B1S2)', tech: 'Cirkonijska (uskopojasna), grijana',
      what: 'Sadržaj kisika iza katalizatora.',
      how: 'Ista vrsta sonde kao prednja. Ispravan katalizator sprema i otpušta kisik te izglađuje oscilacije prednje sonde, pa ova sonda pokazuje stalnih ~0.6–0.7 V.',
      ecu: 'Nadzor učinkovitosti katalizatora: ako stražnji signal počne kopirati prebacivanje prednjeg, katalizator je izgubio sposobnost spremanja kisika. Koristi se i za sporu „vanjsku” korekciju prednje petlje.',
      typical: 'Stalno 0.55–0.75 V',
      fail: 'Kod greške P0420 (učinkovitost katalizatora ispod praga).',
    },
    knock: {
      name: 'Senzor detonacije', tech: 'Piezoelektrični akcelerometar',
      what: 'Vibracije bloka motora u pojasu 5–15 kHz — „kucanje” detonacije, kad neizgorjela smjesa spontano eksplodira umjesto da mirno izgori.',
      how: 'Piezo kristal pričvršćen na blok daje napon kad se trese. ECU sluša samo tijekom „prozora za detonaciju” (otprilike 10–60° nakon GMT svakog cilindra) i filtrira frekvenciju detonacije, pa zna koji je cilindar detonirao.',
      ecu: 'Regulacija detonacije po cilindru: odmah pomiče paljenje tog cilindra 1.5–3° kasnije, a zatim ga polako vraća 0.5–1°/s. Tako osnovna mapa može raditi blizu granice detonacije radi učinkovitosti.',
      typical: 'Pozadinski šum raste s okretajima; detonacija se vidi kao oštar prasak',
      fail: 'ECU primjenjuje sigurnu mapu s jako kasnim paljenjem. Kod greške P0325.',
    },
    egt: {
      name: 'Temperatura ispušnih plinova', tech: 'Termopar / PTC',
      what: 'Temperatura ispuha koji izlazi iz cilindara (ispred turbine na turbo motorima).',
      how: 'Termopar (dva različita metala) daje nekoliko milivolta proporcionalno temperaturi.',
      ecu: 'Zaštita komponenti: iznad ~900 °C ECU obogaćuje smjesu (dodatno gorivo hladi punjenje) kako bi zaštitio turbinu i katalizator. Siromašna smjesa i kasno paljenje povisuju EGT.',
      typical: 'Prazni hod 300–450 °C · Pun gas 800–950 °C',
      fail: 'Modelirana samo zaštita.',
    },
    ect: {
      name: 'Temperatura rashladne tekućine', tech: 'NTC termistor',
      what: 'Temperatura motora, mjerena u rashladnoj tekućini.',
      how: 'NTC termistor: otpor pada kako temperatura raste (~2.5 kΩ na 20 °C, ~200 Ω na 90 °C). S otpornikom u ECU-u čini djelitelj napona, pa napon pada kako se motor zagrijava.',
      ecu: 'Obogaćivanje pri hladnom startu, povišeni prazni hod pri zagrijavanju, kasnije paljenje za grijanje katalizatora, omogućavanje zatvorene petlje (>35 °C), upravljanje ventilatorom hladnjaka i pokazivač na ploči.',
      typical: 'Radna 88–98 °C (termostat se otvara na ~88 °C)',
      fail: 'Prekid pokazuje −40 °C → ECU koristi zamjenskih 80 °C i stalno uključuje ventilator. Kod greške P0118.',
    },
    iat: {
      name: 'Temperatura usisnog zraka', tech: 'NTC termistor',
      what: 'Temperatura zraka u usisnoj grani.',
      how: 'Mali, brzi NTC termistor u struji zraka (često spojen s MAP-om u jedan „TMAP” senzor).',
      ecu: 'Korekcija gustoće zraka za speed-density izračun i zaštita od detonacije — vrući usisni zrak sklon je detonaciji, pa se paljenje pomiče kasnije.',
      typical: 'Vanjska temperatura + 5–20 °C',
      fail: 'Pokazuje −40 °C → zamjenska vrijednost 25 °C. Kod greške P0113.',
    },
    oilp: {
      name: 'Tlak ulja', tech: 'Tlačna sklopka / pretvornik',
      what: 'Tlak ulja za podmazivanje u glavnom kanalu.',
      how: 'Membranska sklopka (zatvara se ispod ~0.4 bar) ili tenzometrijski pretvornik.',
      ecu: 'Lampica upozorenja, a na nekim motorima i upravljanje varijabilnom pumpom ulja. Tlak raste s okretajima i pada kako se ulje zagrijava i razrjeđuje.',
      typical: 'Vrući prazni hod 1–2 bar · 3000 o/min 3–4.5 bar',
      fail: 'Crvena lampica ulja — odmah ugasite motor.',
    },
    oilt: {
      name: 'Temperatura ulja', tech: 'NTC termistor',
      what: 'Temperatura motornog ulja — kasni za temperaturom rashladne tekućine.',
      how: 'NTC termistor u karteru ili kućištu filtra ulja.',
      ecu: 'Procjena trenja i viskoznosti, izračun servisnog intervala, snižen graničnik okretaja dok je motor hladan.',
      typical: '90–120 °C',
      fail: 'Zamjenska vrijednost.',
    },
    fuelp: {
      name: 'Tlak u rampi goriva', tech: 'Tenzometrijski pretvornik',
      what: 'Tlak goriva koje napaja brizgaljke.',
      how: 'Membranski pretvornik na rampi goriva, izlaz 0.5–4.5 V.',
      ecu: 'Protok brizgaljke ovisi o razlici tlaka na njoj. Regulator drži tlak u rampi za stalan iznos iznad tlaka u usisnoj grani, pa je protok po milisekundi stalan. Ako tlak padne, ECU to vidi, a motor radi siromašno.',
      typical: 'Ubrizgavanje u usisnu granu 3–4 bar iznad tlaka u grani',
      fail: 'Slaba pumpa → tlak pada pod opterećenjem, siromašna smjesa pri punom gasu. Kod greške P0087.',
    },
    vbat: {
      name: 'Napon akumulatora / sustava', tech: 'Interni ADC u ECU-u',
      what: 'Napon napajanja.',
      how: 'ECU ga mjeri izravno preko djelitelja napona.',
      ecu: 'Kompenzacija mrtvog vremena brizgaljki (pri niskom naponu sporije se otvaraju), vrijeme punjenja bobine (dulje pri niskom naponu), upravljanje alternatorom.',
      typical: 'Motor ugašen 12.4–12.7 V · Pokretanje 9.5–10.5 V · Motor radi 13.8–14.5 V',
      fail: 'Kvar alternatora → napon polako pada, lampica punjenja. Kod greške P0562.',
    },
    fuellvl: {
      name: 'Razina goriva', tech: 'Plovak + potenciometar',
      what: 'Gorivo u spremniku.',
      how: 'Ručica plovka pomiče klizač po otporničkoj stazi.',
      ecu: 'Pokazivač, upozorenje na malo goriva, omogućavanje EVAP testa nepropusnosti i isključivanje nadzora izostanka paljenja pri vrlo niskoj razini (nedostatak goriva).',
      typical: '0–100 %',
      fail: 'Pogrešan pokazivač.',
    },
    boost: {
      name: 'Tlak punjenja', tech: 'Silicijski senzor deformacije (TMAP)',
      what: 'Tlak u cijevi punjenja iza intercoolera, ispred leptira.',
      how: 'Ista tehnologija kao MAP, ali s rasponom 0–300 kPa.',
      ecu: 'Regulacija tlaka punjenja u zatvorenoj petlji: uspoređuje stvarni tlak s ciljanim i upravlja elektroventilom wastegatea. Otkriva i previsok tlak (sigurnosni prekid) i prenizak tlak (curenja).',
      typical: '100 kPa u praznom hodu · do 250 kPa pri punom tlaku',
      fail: 'Regulacija tlaka onemogućena — wastegate stalno otvoren.',
    },
    cat: {
      name: 'Temperatura stlačenog zraka', tech: 'NTC termistor',
      what: 'Temperatura zraka iza intercoolera.',
      how: 'NTC termistor u cijevi punjenja.',
      ecu: 'Stlačivanje zagrijava zrak (≈120 °C pri 1 bar tlaka punjenja). Intercooler uklanja većinu te topline. ECU ovo koristi za gustoću zraka i zaštitu od detonacije te smanjuje tlak punjenja ako se zrak previše zagrije.',
      typical: 'Vanjska temperatura + 10–40 °C',
      fail: 'Zamjenska vrijednost, smanjeni tlak punjenja.',
    },
    turbo: {
      name: 'Brzina turbopunjača', tech: 'Senzor vrtložnih struja',
      what: 'Brzina vrtnje vratila turbopunjača.',
      how: 'Senzor vrtložnih struja u kućištu kompresora broji vrhove lopatica kompresora koji prolaze.',
      ecu: 'Štiti turbo od prevelike brzine (osobito na visini) i pomaže modelirati turbo rupu.',
      typical: 'Prazni hod 10–20 tis. o/min · puni tlak 160–220 tis. o/min',
      fail: 'Konzervativno ograničenje tlaka punjenja.',
    },
    wgpos: {
      name: 'Položaj wastegatea', tech: 'Hallov senzor položaja',
      what: 'Koliko je otvorena zaklopka wastegatea.',
      how: 'Hallov senzor na šipki aktuatora wastegatea.',
      ecu: 'Wastegate propušta ispuh pored turbine. Otvoren = manje snage turbine = manji tlak punjenja. ECU ga zatvara da podigne tlak, a otvara da zadrži cilj.',
      typical: 'Otvoren (100 %) bez tlaka punjenja · 20–60 % pri držanju tlaka',
      fail: 'Zaglavljen zatvoren → previsok tlak → sigurnosni prekid goriva. Kod greške P0234.',
    },
    vss: {
      name: 'Brzina vozila', tech: 'Hallov / ABS senzori kotača',
      what: 'Brzina vozila.',
      how: 'Hallov ili magnetootpornički senzor koji očitava nazubljeni prsten na izlazu mjenjača ili ABS senzori kotača.',
      ecu: 'Strategija praznog hoda, omogućavanje prekida goriva pri kočenju motorom, prepoznavanje stupnja prijenosa, ograničivač brzine i tempomat.',
      typical: '0–250 km/h',
      fail: 'Brzinomjer i tempomat ne rade.',
    },
    brake: {
      name: 'Sklopka papučice kočnice', tech: 'Dvostruka sklopka',
      what: 'Je li papučica kočnice pritisnuta.',
      how: 'Dva kontakta (normalno otvoren + normalno zatvoren) radi provjere vjerodostojnosti.',
      ecu: 'Prednost kočnice nad gasom, isključenje tempomata, otpuštanje blokade pretvarača momenta.',
      typical: 'Uklj/isklj',
      fail: 'Tempomat onemogućen.',
    },
    acsw: {
      name: 'Zahtjev i tlak klime', tech: 'Sklopka + pretvornik tlaka',
      what: 'Vozač traži klimatizaciju.',
      how: 'Signal tipke plus senzor tlaka rashladnog sredstva.',
      ecu: 'Podiže prazni hod i malo otvara leptir prije uključivanja spojke kompresora (sprječava gašenje), uključuje ventilator hladnjaka.',
      typical: 'Uklj/isklj',
      fail: 'Kompresor onemogućen.',
    },
    rail: {
      name: 'Tlak u rampi (visokotlačni)', tech: 'Tenzometrijski pretvornik, 0–2000 bar',
      what: 'Tlak goriva u zajedničkoj rampi koja napaja sve četiri brizgaljke — 250 bar u praznom hodu, do 1800 bar pri punom opterećenju.',
      how: 'Debela čelična membrana s tenzometrima, uvijena na kraj rampe. Izlaz 0.5–4.5 V.',
      ecu: 'Regulacija tlaka u rampi u zatvorenoj petlji: ECU uspoređuje stvarni i ciljani tlak i upravlja ventilom tlaka / dozirnom jedinicom. Viši tlak finije raspršuje gorivo (manje čađe) i omogućuje ubrizgavanje iste količine u kraćem vremenu.',
      typical: 'Prazni hod 250–350 bar · krstarenje 600–1000 bar · puno opterećenje 1600–1800 bar',
      fail: 'Odstupanje tlaka → nužni način rada. Nizak tlak pod opterećenjem upućuje na dobavnu pumpu ili brizgaljku koja curi (P0087 / P0093).',
    },
    fueltemp: {
      name: 'Temperatura goriva', tech: 'NTC termistor',
      what: 'Temperatura dizela u visokotlačnom sustavu.',
      how: 'NTC termistor u povratu goriva ili kućištu pumpe. Tlačenje goriva na 1800 bar ga zagrijava.',
      ecu: 'Gustoća goriva pada kako se zagrijava, pa ECU korigira ubrizganu količinu. Vrlo vruće gorivo smanjuje dopušteni tlak u rampi.',
      typical: 'Vanjska temperatura + 20–50 °C',
      fail: 'Zamjenska vrijednost.',
    },
    lam: {
      name: 'Širokopojasna lambda sonda', tech: 'Planarna širokopojasna (pumpna ćelija)',
      what: 'Točan omjer zraka i goriva siromašnog dizelskog ispuha — od λ 1.2 pri punom opterećenju do λ 5+ u praznom hodu.',
      how: 'Pumpna ćelija premješta ione kisika kako bi referentnu ćeliju držala na λ = 1; struja pumpe proporcionalna je sadržaju kisika u ispuhu, pa mjeri bilo koju λ, a ne samo bogato/siromašno.',
      ecu: 'Korigira očitanje MAF-a i ograničivač dima te provjerava odstupanje količine brizgaljki. Dizel nikad ne radi na λ = 1 — nema petlje s prebacivanjem.',
      typical: 'Prazni hod λ 3–6 · puno opterećenje λ 1.2–1.4',
      fail: 'Zamjenski model zraka, smanjeni moment.',
    },
    egt2: {
      name: 'Temperatura na ulazu u DPF', tech: 'Termopar / PTC',
      what: 'Temperatura ispuha iza oksidacijskog katalizatora (DOC), neposredno ispred filtra čestica.',
      how: 'Ista vrsta senzora kao EGT ispred turbine.',
      ecu: 'Upravlja aktivnom regeneracijom: naknadno ubrizgano gorivo izgara na DOC-u i podiže ovu temperaturu na ~600 °C kako bi čađa u DPF-u izgorjela.',
      typical: 'Normalna vožnja 200–450 °C · regeneracija 580–650 °C',
      fail: 'Regeneracija onemogućena.',
    },
    dpfdp: {
      name: 'Diferencijalni tlak DPF-a', tech: 'Senzor diferencijalnog tlaka',
      what: 'Pad tlaka na dizelskom filtru čestica.',
      how: 'Dva crijeva — ispred i iza filtra — vode do jednog diferencijalnog senzora. Što je više čađe, veći je pad tlaka za isti protok ispuha.',
      ecu: 'Procjenjuje količinu čađe (zajedno s modelom nastajanja čađe). Kad je filtar pun ~24 g, ECU pokreće aktivnu regeneraciju; iznad ~45 g pali lampicu DPF-a i ograničava snagu.',
      typical: 'Prazni hod 5–20 mbar · puno opterećenje 50–250 mbar (raste s čađom)',
      fail: 'Čađa se procjenjuje samo iz modela. Kod greške P2463 ako je filtar prepunjen.',
    },
    egrpos: {
      name: 'Položaj EGR ventila', tech: 'Hallov senzor položaja',
      what: 'Koliko je otvoren ventil za povrat ispušnih plinova.',
      how: 'Hallov senzor na osovini ventila; ventil pomiče električni motor.',
      ecu: 'EGR vraća ohlađeni ispuh u usis. On istiskuje kisik, snižava temperaturu izgaranja i NOx. ECU otvara ventil dok očitanje MAF-a ne padne na zadanu vrijednost svježeg zraka.',
      typical: 'Prazni hod / djelomično opterećenje 20–60 % · puno opterećenje 0 %',
      fail: 'Zaglavljen otvoren → dim i manje snage (P0402). Zaglavljen zatvoren → visok NOx, MAF iznad cilja (P0401).',
    },
    vgtpos: {
      name: 'Položaj lopatica VGT-a', tech: 'Senzor položaja na aktuatoru lopatica',
      what: 'Položaj lopatica turbine s promjenjivom geometrijom.',
      how: 'Pomične lopatice oko kola turbine mijenjaju efektivni presjek sapnice. Zatvorene lopatice ubrzavaju protok ispuha na kolo → veći tlak na niskim okretajima; otvorene smanjuju protutlak na visokim okretajima.',
      ecu: 'Regulacija tlaka punjenja u zatvorenoj petlji: kao wastegate, ali umjesto ispuštanja ispuha mijenja koliko snažno ispuh pogoni turbinu — pa gotovo nema turbo rupe.',
      typical: 'Prazni hod otvoreno · puno opterećenje na niskim okretajima uglavnom zatvoreno · visoki okretaji djelomično otvoreno',
      fail: 'Zaglavljene zatvorene → previsok tlak i nužni način (P0234); zaglavljene otvorene → nema tlaka (P0299).',
    },
    amb: {
      name: 'Vanjska temperatura', tech: 'NTC termistor',
      what: 'Temperatura vanjskog zraka.',
      how: 'Termistor iza prednjeg branika.',
      ecu: 'Strategije hladnog starta, procjena učinkovitosti intercoolera i prikaz na ploči.',
      typical: '−30 do +50 °C',
      fail: 'Zamjenska vrijednost.',
    },
  };

  const actuators = {
    inj: { name: 'Brizgaljke ×4', desc: 'Elektromagnetski ventili koji ubrizgavaju gorivo u usisni kanal svakog cilindra. ECU određuje koliko dugo ostaju otvorene (trajanje impulsa) i kada (trenutak ubrizgavanja, u stupnjevima radilice). Sekvencijalno: svaki cilindar ubrizgava jednom po ciklusu, neposredno prije otvaranja usisnog ventila.' },
    coil: { name: 'Bobine ×4', desc: 'Bobina na svakoj svjećici. ECU propušta struju kroz primarni namot tijekom „vremena punjenja” kako bi stvorio magnetsko polje, a zatim je prekida — polje koje se urušava inducira 25–40 kV u sekundarnom namotu i svjećica preskače. Pretpaljenje = stupnjevi prije GMT.' },
    etc: { name: 'Elektronički leptir (ETC)', desc: 'Istosmjerni motor postavlja zaklopku leptira. ECU regulira položaj pomoću oba kanala TPS-a. U praznom hodu ECU sam otvara leptir nekoliko posto kako bi održao ciljani prazni hod.' },
    pump: { name: 'Relej pumpe goriva', desc: 'Puni rampu 2 s pri uključenju kontakta, a zatim radi samo dok ECU vidi impulse radilice (sigurnost: zaustavlja gorivo ako se motor ugasi ili nakon sudara).' },
    fan: { name: 'Ventilator hladnjaka', desc: 'Uključuje se iznad ~98 °C rashladne tekućine, isključuje ispod ~93 °C (histereza) te uvijek kad radi klima.' },
    vvt: { name: 'Ventil za upravljanje VVT-om', desc: 'Usmjerava tlak ulja u zakretač bregastog kako bi pomaknuo usisno bregasto vratilo naprijed ili natrag. Veći pomak naprijed pri srednjim okretajima i opterećenju poboljšava moment i dodaje unutarnji EGR.' },
    wg: { name: 'Elektroventil wastegatea', desc: 'PWM ventil koji upravlja aktuatorom wastegatea. Veći radni ciklus drži wastegate zatvorenim kako bi se podigao tlak punjenja.' },
    bov: { name: 'Blow-off / diverter ventil', desc: 'Kad se leptir naglo zatvori pod tlakom punjenja, stlačeni zrak nema kamo. Ventil ga ispušta kako bi spriječio pumpanje kompresora (poznati „pššš”).' },
    o2h: { name: 'Grijači lambda sondi', desc: 'Otpornički grijači dovode cirkonijske elemente na 600–750 °C u nekoliko sekundi kako bi zatvorena petlja mogla početi rano.' },
    alt: { name: 'Upravljanje uzbudom alternatora', desc: 'Regulira napon punjenja oko 14 V; punjenje dodaje opterećenje momentom na radilicu.' },
    acc: { name: 'Spojka kompresora klime', desc: 'Uključuje se nakon što je prazni hod podignut.' },
    dinj: { name: 'Piezo brizgaljke ×4', desc: 'Izravno ubrizgavanje u cilindar pri do 1800 bar. Piezo stupci otvaraju sapnicu za ~0.1 ms, pa je moguće više ubrizgavanja po ciklusu: malo predubrizgavanje (tiše izgaranje), glavno ubrizgavanje (moment) i kasna naknadna ubrizgavanja za grijanje DPF-a tijekom regeneracije.' },
    pcv: { name: 'Ventil za regulaciju tlaka u rampi', desc: 'Dozira koliko goriva visokotlačna pumpa dobavlja u rampu i ispušta višak, držeći rampu na ciljanom tlaku ECU-a.' },
    vgt: { name: 'Aktuator lopatica VGT-a', desc: 'Pomiče lopatice turbine. Zatvaranje podiže tlak punjenja; ECU zatvara petlju prema senzoru tlaka punjenja.' },
    egr: { name: 'EGR ventil', desc: 'Propušta ohlađeni ispuh natrag u usis radi smanjenja NOx-a. ECU ga otvara dok MAF ne padne na zadanu vrijednost svježeg zraka; zatvara se pri punom opterećenju gdje treba svaki gram kisika.' },
    glow: { name: 'Grijači ×4', desc: 'Grijaće šipke u svakom cilindru. Hladan dizel samom kompresijom možda ne dosegne temperaturu samozapaljenja, pa grijači predgrijavaju komore prije pokretanja i griju još neko vrijeme nakon starta (manje dima i buke).' },
    mil: { name: 'MIL (lampica check engine)', desc: 'Svijetli kod kvarova važnih za emisije. Treperi tijekom izostanka paljenja koji oštećuje katalizator.' },
  };

  const faults = {
    ckp: { name: 'Prekid CKP senzora', hint: 'Nema signala radilice → nema iskre ni goriva. Motor se gasi.' },
    cmp: { name: 'Kvar CMP senzora', hint: 'Prelazak na skupno ubrizgavanje i izgubljenu iskru. Pogledajte dijagram.' },
    misfire3: { name: 'Bobina #3 u kvaru', hint: 'Izostanak paljenja otkriven preko padova brzine radilice, brizgaljka 3 isključena, MIL treperi.' },
    maf: { name: 'Kvar MAF senzora', hint: 'ECU prelazi na speed-density (MAP) izračun zraka.' },
    map: { name: 'Kvar MAP senzora', hint: 'MAF se i dalje koristi; samo kod vjerodostojnosti.' },
    tps: { name: 'Senzori leptira se ne slažu', hint: 'Motor leptira isključen — nužni rad s fiksnim otvorom.' },
    ect: { name: 'Prekid ECT senzora', hint: 'Pokazuje −40 °C. ECU koristi 80 °C, ventilator stalno radi.' },
    iat: { name: 'Prekid IAT senzora', hint: 'Pokazuje −40 °C. ECU koristi 25 °C.' },
    o2: { name: 'Lambda sonda u kvaru (zaglavljena na siromašnom)', hint: 'Korekcije idu do +25 %, zatim ECU odustaje → otvorena petlja.' },
    cat: { name: 'Istrošen katalizator', hint: 'Stražnja lambda počinje kopirati prebacivanje prednje.' },
    knocksensor: { name: 'Kvar senzora detonacije', hint: 'Sigurna (kasnija) mapa paljenja posvuda.' },
    vacleak: { name: 'Curenje podtlaka (nemjereni zrak)', hint: 'MAF ne vidi dodatni zrak → siromašno → korekcije goriva rastu.' },
    fuelpump: { name: 'Slaba pumpa goriva', hint: 'Tlak u rampi pada pod opterećenjem → siromašno pri punom gasu.' },
    alt: { name: 'Kvar alternatora', hint: 'Napon akumulatora pada, mrtvo vrijeme brizgaljki raste.' },
    oil: { name: 'Niska razina ulja', hint: 'Lampica tlaka ulja u praznom hodu.' },
    thermostat: { name: 'Termostat zaglavljen otvoren', hint: 'Motor nikad ne postiže radnu temperaturu.' },
    wgstuck: { name: 'Wastegate zaglavljen zatvoren', hint: 'Tlak punjenja divlja → prekid zbog previsokog tlaka.' },
    glowplug: { name: 'Grijači u kvaru', hint: 'Otkriva se pri uključenju kontakta; težak hladan start uz bijeli dim.' },
    egropen: { name: 'EGR ventil zaglavljen otvoren', hint: 'Premalo svježeg zraka: ograničivač dima reže gorivo → manje snage, čađa.' },
    egrclosed: { name: 'EGR ventil zaglavljen zatvoren', hint: 'MAF ostaje iznad zadanog; NOx raste.' },
    dpfclog: { name: 'DPF začepljen pepelom', hint: 'Pad tlaka daleko previsok; regeneracija ga ne može očistiti → nužni način.' },
    injleak3: { name: 'Brizgaljka #3 curi', hint: 'Gorivo kaplje u cilindar 3: neravnomjeran prazni hod, dim, pumpa dobavlja više nego što se ubrizgava.' },
    vgtstuck: { name: 'Lopatice VGT-a zaglavljene zatvorene', hint: 'Tlak punjenja prelazi cilj pod opterećenjem → zaštita od previsokog tlaka.' },
    boostleak: { name: 'Curenje tlaka punjenja (pukla cijev)', hint: 'Ne postiže ciljani tlak; izmjereni zrak bježi → bogato.' },
  };

  const dtc = {
    P0335: 'Senzor položaja radilice A – strujni krug',
    P0340: 'Senzor položaja bregastog vratila A – strujni krug',
    P0303: 'Otkriven izostanak paljenja u cilindru 3',
    P0102: 'Mjerač mase zraka – nizak signal',
    P0107: 'MAP senzor – nizak signal',
    P0121: 'Senzor položaja leptira A/B – nepodudaranje',
    P0118: 'Senzor temperature rashladne tekućine – visok signal',
    P0113: 'Senzor temperature usisnog zraka – visok signal',
    P0134: 'Lambda sonda B1S1 – nema aktivnosti',
    P0420: 'Učinkovitost katalizatora ispod praga (B1)',
    P0325: 'Senzor detonacije 1 – strujni krug',
    P0171: 'Sustav presiromašan (B1)',
    P0172: 'Sustav prebogat (B1)',
    P0087: 'Tlak u rampi goriva prenizak',
    P0562: 'Napon sustava nizak',
    P0128: 'Rashladna tekućina ispod radne temperature termostata',
    P0234: 'Turbopunjač – previsok tlak punjenja',
    P0299: 'Turbopunjač – prenizak tlak punjenja',
    P0670: 'Krug upravljanja grijačima',
    P0401: 'Nedovoljan protok EGR-a',
    P0402: 'Prevelik protok EGR-a',
    P2463: 'Nakupljanje čađe u DPF-u',
    P0093: 'Otkriveno curenje goriva — veliko curenje',
  };

  const groups = {
    position: 'Položaj i brzina motora',
    air: 'Mjerenje zraka',
    turbo: 'Turbo / stlačeni zrak',
    exhaust: 'Izgaranje i ispuh',
    temp: 'Temperature i podmazivanje',
    fuel: 'Sustav goriva',
    driver: 'Vozač i vozilo',
  };

  ECU.INFO_HR = { sensors, actuators, faults };

  // short names are also reachable through ECU.t(englishText)
  const HR = ECU.HR;
  ECU.SENSOR_GROUPS.forEach((g) => { if (groups[g.id]) HR[g.name] = groups[g.id]; });
  ECU.SENSORS.forEach((s) => { if (sensors[s.id]) HR[s.name] = sensors[s.id].name; });
  ECU.ACTUATORS.forEach((a) => { if (actuators[a.id]) HR[a.name] = actuators[a.id].name; });
  ECU.FAULTS.forEach((f) => { if (faults[f.id]) HR[f.name] = faults[f.id].name; });
  Object.keys(dtc).forEach((code) => { if (ECU.DTC_TEXT[code]) HR[ECU.DTC_TEXT[code]] = dtc[code]; });
})();
